#!/bin/bash

#Backend array_of_objects(list)
array_of_objects=(
	"Propane Tank" 
	"Gumball Machine" 
	"Video game controller" 
	"Screwdriver" 
	"Pinata" 
	"Aspirin" 
	"Baseball" 
	"Invitation" 
	"Latern" 
	"Toolbox"
)
tab_m="\t\t\t\t"
#Backend Option Functions
	


echo "H) save this bag!(answer with the refered letter)"
echo "I) load a previously saved bag"
echo "J) List all the saved bags"

read answer3

if [[ $answer3 == "H" ]] || [[ $answer3 == "h" ]]; then

	echo -e "
	K) what do you want to name this save_bag 
	"
	read save_name
	touch /home/sasuke/Bashing_Boxes/data/$save_name.sh
	declare -p array_of_objects > /home/sasuke/Bashing_Boxes/data/$save_name.sh
	ls /home/sasuke/Bashing_Boxes/data


elif [[ $answer3 == "I" ]] || [[ $answer3 == "i" ]] then 
	echo -e "
				Here are the saved bags
	"				
	sleep 2
	ls /home/sasuke/Bashing_Boxes/data
	read -p "type the name of your bag   " save_name

	if [[ "$save_name" != *.sh ]]; then 
		save_name="${save_name}.sh"
	fi
		save_path="/home/sasuke/Bashing_Boxes/data/$save_name"
		
		if [[ -f /home/sasuke/Bashing_Boxes/data/$save_name ]] then

	 		source "/home/sasuke/Bashing_Boxes/data/$save_name"
	 		echo -e "$tab_m""This array has ben loaded" 
	 		echo ${array_of_objects[@]}
		else
			echo -e "\nfile doesnt exist\n"
		fi


elif  [[ $answer3 == "J" ]] || [[ $answer3 == "j"  ]] then
	 ls /home/sasuke/Bashing_Boxes/data


	



fi 
		


Greetings/option1(){
	echo "Hi Traveller what's your name"
	read name

	echo "$name want to see whats in my magic bag (awnser with the refered letter)"
	echo "A) yes"
	echo "B) no"
	echo "C) leave" 
}

reads(){
	read answer
}

Answer1(){ 
case $answer in 
A | a) echo "${array_of_objects[@]}"
sleep 3
option2
;;
B | b) echo "alright" 
sleep 3
exit
;;
C | c) exit
;;
*) echo "what?"
;;
esac
}

option2(){ 
echo e "


D) want to put something in my magic bag (answer with the refered letter)
E) want to remove a specific item from my magic bag
F) want to view a specfic item
G) want to remove an item at the end of the bag
" 
echo -e "

"
reads2 }

reads2(){
read answer2
Answer2
}

Answer2D(){ 
case $answer2 in 
D | d) echo -e " 


what do you want to add to the bag"
read item
 array_of_objects+=("$item")
 ls "${array_of_objects[@]}"
;;

*)echo "Try again"
;;
esac }



if [[ $answer == "A" ]] || [[ $answer == "a" ]]; then 
	echo "${array_of_objects[@]}"

	sleep 2

	echo -e "

	"
	echo "D) want to put something in my magic bag (answer with the refered letter)"
	echo "E) want to remove a specific item from my magic bag"
	echo "F) want to view a specfic item"
	echo "G) want to remove an item at the end of the bag"

	read answer2







	if [[ $answer2 == "D" ]] || [[ $answer2 == "d" ]] then

		echo " "
		echo " "
		echo " "
		echo "what do you want to add to the bag?"
		read item
		array_of_objects+=("$item")
		sleep 1
		echo -e "${array_of_objects[@]}"

		echo -e "


		"
		option3

	

	


	elif [[ $answer2 == "E" ]] || [[ $answer2 == "e" ]] then
		echo -e "


		"
		echo "what do you want to remove from the bag?"
		echo -e "

		"
		echo "${array_of_objects[@]}"
		read -p "enter a number you want to remove from my bag between 0-9: " number
		unset array_of_objects[$((number-1))]
		echo -e "${array_of_objects[@]}"

		echo -e "

		"
		option3






	elif [[ $answer2 == "F" ]] || [[ $answer2 == "f" ]]; then
		echo "pick any number from the 0-9 to inspect it"
		read number2
		echo "${array_of_objects[number2]}"
		echo -e "

		"

		option3






	elif [[ $answer2 == "G" ]] || [[ $answer2 == "g" ]]; then

		unset 'array_of_objects[$((${#array_of_objects[@]} - 1))]'
			echo -e "${array_of_objects[@]}"



		echo -e"

		"
		option3



	fi





elif [[ $anwser == "B" ]] || [[ $anwser == "b" ]]; then
	echo "alright"
	sleep 3 
	exit
 	#statements [[$awnser == "B"]];  
elif [[ $anwser == "C" ]]; then
	exit 
fi
